/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Plugins__factory } from "./IERC20Plugins__factory";
export { IPlugin__factory } from "./IPlugin__factory";
