/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPlugin,
  IPluginInterface,
} from "../../../../../@1inch/token-plugins/contracts/interfaces/IPlugin";

const _abi = [
  {
    inputs: [],
    name: "token",
    outputs: [
      {
        internalType: "contract IERC20Plugins",
        name: "erc20",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "updateBalances",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPlugin__factory {
  static readonly abi = _abi;
  static createInterface(): IPluginInterface {
    return new Interface(_abi) as IPluginInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPlugin {
    return new Contract(address, _abi, runner) as unknown as IPlugin;
  }
}
