/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libs from "./libs";
export type { libs };
export type { ERC20Plugins } from "./ERC20Plugins";
export type { Plugin } from "./Plugin";
