/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../common";
import type {
  ReentrancyGuardLib,
  ReentrancyGuardLibInterface,
} from "../../../../../../@1inch/token-plugins/contracts/libs/ReentrancyGuard.sol/ReentrancyGuardLib";

const _abi = [
  {
    inputs: [],
    name: "ReentrantCall",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220ba1188e1d769064f3657ed27448d1b677277bfcb3979e1d27bb743128ee11d9864736f6c63430008140033";

type ReentrancyGuardLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReentrancyGuardLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReentrancyGuardLib__factory extends ContractFactory {
  constructor(...args: ReentrancyGuardLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ReentrancyGuardLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReentrancyGuardLib__factory {
    return super.connect(runner) as ReentrancyGuardLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrancyGuardLibInterface {
    return new Interface(_abi) as ReentrancyGuardLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReentrancyGuardLib {
    return new Contract(address, _abi, runner) as unknown as ReentrancyGuardLib;
  }
}
